### ISSUE TITLE
Why do i see servers in Server Groups?

### ISSUE THREAD

**Issue by Duke-M-commits** [ReactiveDrop/reactivedrop_translations#952]
When I start the game and click on the list of group-servers in the lower right of the screen, I get some servers, but the descriptions says I can join servers of "my Steam  Groups". But I'm in no Steam Groups which are related to AS.

Is the description text maybe outdated?

![image](https://github.com/ReactiveDrop/reactivedrop_translations/assets/69652463/18c4fed3-1994-4e9f-bd7d-71a98cea1c37)

**Comment by BenLubar** [comment]
I think most servers use the official game group as their designated group ID, so if you're following the game on Steam they'll show up in there. We're removing the concept of a steam group server from the client in next year's anniversary update because it's not really useful (it'll just query for servers rather than checking each group you're in and game you follow to see if there are servers with that tag).

**Comment by Duke-M-commits** [comment]
Ok
